import { describe, expect, it } from 'vitest';
import { newModel } from '../model/factory';
import type { ModelSpec } from '../model/types';
import { modelCost, type Context } from './engine';

interface Example {
  name: string;
  trait: string | null;
  expansion?: boolean;
  expected: number;
  /** Cost printed in the PDF when it disagrees with the cost tables */
  published?: number;
  spd: 1 | 2 | 3;
  def: string;
  fp: string;
  prw: string;
  will: string;
  ranged?: string[];
  close?: string[];
  equip?: string[];
  powers?: string[];
  leader?: boolean;
}

const E = (e: Example) => e;
const examples: Example[] = [
  // Alien X-Terminators (soldiers), core p.12
  E({
    name: 'Rookie',
    trait: 'soldiers',
    expected: 10,
    spd: 2,
    def: '2d6',
    fp: '2d8',
    prw: '2d6',
    will: '2d6',
    ranged: ['auto-rifle'],
    equip: ['grenade'],
  }),
  E({
    name: 'Ranger',
    trait: 'soldiers',
    expected: 19,
    spd: 3,
    def: '2d8',
    fp: '2d8',
    prw: '2d8',
    will: '2d6',
    ranged: ['shotgun'],
    close: ['powered-weapon'],
    equip: ['grenade'],
  }),
  E({
    name: 'Heavy',
    trait: 'soldiers',
    expected: 17,
    spd: 2,
    def: '2d8',
    fp: '2d8',
    prw: '2d8',
    will: '2d6',
    ranged: ['rocket-launcher'],
    close: ['large-melee-weapon'],
    equip: ['heavy-armor'],
  }),
  E({
    name: 'Sniper',
    trait: 'soldiers',
    expected: 16,
    spd: 2,
    def: '2d6',
    fp: '2d10',
    prw: '2d6',
    will: '2d6',
    ranged: ['sniper-rifle'],
    equip: ['stealth-suit'],
  }),
  E({
    name: 'Psychic Trooper',
    trait: 'soldiers',
    expected: 19,
    leader: true,
    spd: 2,
    def: '2d8',
    fp: '2d8',
    prw: '2d6',
    will: '2d10',
    ranged: ['heavy-rifle'],
    equip: ['heavy-armor'],
    powers: ['prescience', 'telekinesis'],
  }),
  // Aliens (mutants)
  E({
    name: 'MIB',
    trait: 'mutants',
    expected: 12,
    spd: 3,
    def: '2d6',
    fp: '2d8',
    prw: '2d6',
    will: '2d6',
    ranged: ['energy-pistol'],
  }),
  E({
    name: 'Grey',
    trait: 'mutants',
    expected: 15,
    spd: 2,
    def: '2d6',
    fp: '2d8',
    prw: '2d6',
    will: '2d8',
    ranged: ['energy-pistol'],
    powers: ['fear', 'mind-control'],
  }),
  E({
    name: 'Ophidian',
    trait: 'mutants',
    expected: 17,
    spd: 3,
    def: '2d8',
    fp: '2d8',
    prw: '2d8',
    will: '2d6',
    ranged: ['energy-rifle'],
    close: ['whip-tail'],
  }),
  E({
    name: 'Brute',
    trait: 'mutants',
    expected: 18,
    spd: 2,
    def: '2d10',
    fp: 'none',
    prw: '2d10',
    will: '2d6',
    close: ['horrible-claws-teeth'],
  }),
  // The PDF prints 18; the cost tables give 17.
  E({
    name: 'Astral',
    trait: 'mutants',
    expected: 17,
    published: 18,
    leader: true,
    spd: 2,
    def: '2d8',
    fp: 'none',
    prw: '2d6',
    will: '2d10',
    equip: ['psychic-focus'],
    powers: ['mind-stab', 'teleport'],
  }),
  // Darkest Future
  E({
    name: 'Trooper',
    trait: 'fanatics',
    expected: 10,
    spd: 2,
    def: '2d6',
    fp: '2d8',
    prw: '2d6',
    will: '2d6',
    ranged: ['auto-rifle'],
  }),
  E({
    name: 'Veteran Trooper',
    trait: 'fanatics',
    expected: 14,
    spd: 2,
    def: '2d6',
    fp: '2d8',
    prw: '2d6',
    will: '2d8',
    ranged: ['heavy-rifle'],
    equip: ['targeting-reticule'],
  }),
  E({
    name: 'Supersoldier',
    trait: 'fanatics',
    expected: 20,
    spd: 2,
    def: '2d8',
    fp: '2d10',
    prw: '2d8',
    will: '2d8',
    ranged: ['heavy-rifle'],
    close: ['melee-weapon'],
  }),
  E({
    name: 'Adjudicator',
    trait: 'fanatics',
    expected: 25,
    leader: true,
    spd: 2,
    def: '2d8',
    fp: '2d10',
    prw: '2d8',
    will: '2d10',
    ranged: ['heavy-rifle'],
    close: ['powered-weapon'],
    powers: ['fear', 'healing'],
  }),
  // Neon City
  E({
    name: 'Razor Girl',
    trait: 'cyborgs',
    expected: 14,
    spd: 3,
    def: '2d6',
    fp: '2d8',
    prw: '2d6',
    will: '2d6',
    ranged: ['auto-pistol'],
    close: ['melee-weapon'],
    equip: ['cybernetics', 'targeting-reticule'],
  }),
  E({
    name: 'Razor Queen',
    trait: 'cyborgs',
    expected: 23,
    leader: true,
    spd: 3,
    def: '2d8',
    fp: 'none',
    prw: '2d10',
    will: '2d8',
    close: ['horrible-claws-teeth'],
    equip: ['cybernetics', 'heavy-armor', 'jump-pack'],
  }),
  E({
    name: 'Steroid Boy',
    trait: 'living-weapons',
    expected: 14,
    spd: 2,
    def: '2d8',
    fp: '2d8',
    prw: '2d8',
    will: '2d6',
    ranged: ['auto-rifle'],
  }),
  E({
    name: 'Steroid King',
    trait: 'living-weapons',
    expected: 25,
    leader: true,
    spd: 2,
    def: '2d10',
    fp: '2d8',
    prw: '2d10',
    will: '2d8',
    ranged: ['autocannon'],
    equip: ['heavy-armor'],
  }),
  E({
    name: 'Zombie',
    trait: 'undead',
    expected: 10,
    spd: 1,
    def: '2d6',
    fp: 'none',
    prw: '2d8',
    will: '2d6',
    close: ['claws-teeth'],
  }),
  // The PDF prints 24; the cost tables give 25.
  E({
    name: 'Vampire',
    trait: 'undead',
    expected: 25,
    published: 24,
    leader: true,
    spd: 3,
    def: '2d8',
    fp: 'none',
    prw: '2d10',
    will: '2d8',
    close: ['horrible-claws-teeth'],
    equip: ['jump-pack'],
    powers: ['meat-puppet', 'mind-control'],
  }),
  // Fan expansion p.14
  E({
    name: 'Princess Rebellia',
    trait: 'plucky-rebels',
    expansion: true,
    expected: 18,
    leader: true,
    spd: 2,
    def: '2d6',
    fp: '2d8',
    prw: '2d6',
    will: '2d10',
    ranged: ['energy-pistol'],
    equip: ['comms-unit', 'psychic-focus'],
    powers: ['prescience'],
  }),
  E({
    name: 'Luke Starweirder',
    trait: 'plucky-rebels',
    expansion: true,
    expected: 20,
    spd: 2,
    def: '2d8',
    fp: 'none',
    prw: '2d8',
    will: '2d10',
    close: ['powered-weapon'],
    equip: ['laser-sword'],
    powers: ['telekinesis', 'prescience'],
  }),
  E({
    name: 'Chow-baka',
    trait: 'plucky-rebels',
    expansion: true,
    expected: 24,
    spd: 2,
    def: '2d8',
    fp: '2d10',
    prw: '2d10',
    will: '2d8',
    ranged: ['heavy-rifle'],
    close: ['claws-teeth'],
    equip: ['grenade'],
  }),
  E({
    name: 'Han Loco',
    trait: 'plucky-rebels',
    expansion: true,
    expected: 12,
    spd: 2,
    def: '2d6',
    fp: '2d8',
    prw: '2d6',
    will: '2d6',
    ranged: ['energy-pistol'],
    equip: ['targeting-reticule'],
  }),
  // The rest of the expansion's example warbands (pp.14-15). Where the printed cost
  // disagrees with the cost tables, `expected` is the table value and `published` the PDF's.
  // Imperial Empire (Imperial Numbers)
  E({
    name: 'Darn Father',
    trait: 'imperial-numbers',
    expansion: true,
    expected: 24,
    published: 25,
    leader: true,
    spd: 2,
    def: '2d8',
    fp: 'none',
    prw: '2d10',
    will: '2d8',
    close: ['powered-weapon'],
    equip: ['laser-sword'],
    powers: ['telekinesis', 'mind-stab', 'prescience', 'fear'],
  }),
  E({
    name: 'Darn Sillious',
    trait: 'imperial-numbers',
    expansion: true,
    expected: 20,
    published: 19,
    spd: 2,
    def: '2d6',
    fp: 'none',
    prw: '2d8',
    will: '2d10',
    equip: ['psychic-focus'],
    powers: ['telekinesis', 'fear', 'mind-stab', 'prescience'],
  }),
  E({
    name: 'Imperial Trooper',
    trait: 'imperial-numbers',
    expansion: true,
    expected: 10,
    spd: 2,
    def: '2d6',
    fp: '2d8',
    prw: '2d6',
    will: '2d6',
    ranged: ['auto-rifle'],
  }),
  E({
    name: 'Imperial Scout',
    trait: 'imperial-numbers',
    expansion: true,
    expected: 12,
    published: 11,
    spd: 2,
    def: '2d6',
    fp: '2d8',
    prw: '2d6',
    will: '2d6',
    ranged: ['sniper-rifle'],
  }),
  E({
    name: 'Rebel Fighter',
    trait: 'plucky-rebels',
    expansion: true,
    expected: 10,
    spd: 2,
    def: '2d6',
    fp: '2d8',
    prw: '2d6',
    will: '2d6',
    ranged: ['heavy-pistol'],
  }),
  // Crime Lords (Mutants)
  E({
    name: 'Big Pappa',
    trait: 'mutants',
    expansion: true,
    expected: 19,
    published: 17,
    leader: true,
    spd: 1,
    def: '2d10',
    fp: 'none',
    prw: '2d6',
    will: '2d10',
    close: ['claws-teeth'],
    equip: ['heavy-armor', 'comms-unit'],
  }),
  E({
    name: 'Slave Driver',
    trait: 'mutants',
    expansion: true,
    expected: 10,
    spd: 2,
    def: '2d6',
    fp: '2d8',
    prw: '2d6',
    will: '2d6',
    ranged: ['heavy-pistol'],
    close: ['whip-tail'],
  }),
  E({
    name: 'Pigman',
    trait: 'mutants',
    expansion: true,
    expected: 11,
    spd: 2,
    def: '2d6',
    fp: '2d8',
    prw: '2d6',
    will: '2d6',
    ranged: ['energy-rifle'],
    close: ['claws-teeth'],
  }),
  E({
    name: 'Bounty Hunter',
    trait: 'mutants',
    expansion: true,
    expected: 15,
    spd: 3,
    def: '2d8',
    fp: '2d8',
    prw: '2d6',
    will: '2d6',
    ranged: ['energy-pistol'],
    equip: ['jump-pack'],
  }),
  // Xenos Cult (Fanatics; the two-column layout of the PDF makes the Xenos models look like Mutants)
  E({
    name: 'Cult Father',
    trait: 'fanatics',
    expansion: true,
    expected: 21,
    leader: true,
    spd: 2,
    def: '2d6',
    fp: '2d8',
    prw: '2d6',
    will: '2d10',
    ranged: ['energy-pistol'],
    close: ['melee-weapon'],
    equip: ['psychic-focus'],
    powers: ['prescience', 'fear', 'mind-control'],
  }),
  E({
    name: 'Xenos',
    trait: 'fanatics',
    expansion: true,
    expected: 19,
    spd: 3,
    def: '2d8',
    fp: 'none',
    prw: '2d10',
    will: '2d6',
    close: ['horrible-claws-teeth'],
    equip: ['cybernetics'],
  }),
  E({
    name: 'Hybrid',
    trait: 'fanatics',
    expansion: true,
    expected: 15,
    spd: 2,
    def: '2d6',
    fp: '2d8',
    prw: '2d8',
    will: '2d6',
    ranged: ['flamer'],
    close: ['claws-teeth'],
  }),
  E({
    name: 'Cultist',
    trait: 'fanatics',
    expansion: true,
    expected: 10,
    spd: 2,
    def: '2d6',
    fp: '2d8',
    prw: '2d6',
    will: '2d6',
    ranged: ['auto-rifle'],
  }),
  // Sporks (Heavily Armed)
  E({
    name: 'Big Bozz',
    trait: 'heavily-armed',
    expansion: true,
    expected: 19,
    leader: true,
    spd: 2,
    def: '2d8',
    fp: '2d8',
    prw: '2d8',
    will: '2d8',
    ranged: ['heavy-pistol'],
    close: ['large-powered-weapon'],
    equip: ['heavy-armor'],
  }),
  E({
    name: 'Ladz',
    trait: 'heavily-armed',
    expansion: true,
    expected: 11,
    spd: 2,
    def: '2d6',
    fp: '2d8',
    prw: '2d6',
    will: '2d6',
    ranged: ['heavy-pistol'],
    close: ['melee-weapon'],
    equip: ['heavy-armor'],
  }),
  E({
    name: 'Stormin Ladz',
    trait: 'heavily-armed',
    expansion: true,
    expected: 16,
    spd: 3,
    def: '2d6',
    fp: '2d8',
    prw: '2d8',
    will: '2d6',
    ranged: ['heavy-pistol'],
    close: ['powered-weapon'],
    equip: ['jump-pack'],
  }),
  E({
    name: 'Little Gitz',
    trait: 'heavily-armed',
    expansion: true,
    expected: 9,
    spd: 2,
    def: '2d6',
    fp: '2d8',
    prw: '2d6',
    will: '2d6',
    ranged: ['auto-pistol'],
  }),
  // Stumpies (Blue Collar)
  E({
    name: 'Karl',
    trait: 'blue-collar',
    expansion: true,
    expected: 22,
    published: 21,
    leader: true,
    spd: 1,
    def: '2d8',
    fp: '2d8',
    prw: '2d8',
    will: '2d10',
    ranged: ['energy-pistol'],
    close: ['powered-weapon'],
    equip: ['cybernetics', 'heavy-armor'],
  }),
  E({
    name: 'Dwarf Trooper',
    trait: 'blue-collar',
    expansion: true,
    expected: 12,
    published: 11,
    spd: 1,
    def: '2d6',
    fp: '2d8',
    prw: '2d6',
    will: '2d8',
    ranged: ['energy-rifle'],
  }),
  E({
    name: 'Dwarf Demolisher',
    trait: 'blue-collar',
    expansion: true,
    expected: 16,
    published: 15,
    spd: 1,
    def: '2d6',
    fp: '2d10',
    prw: '2d6',
    will: '2d8',
    ranged: ['rocket-launcher'],
    equip: ['targeting-reticule'],
  }),
  E({
    name: 'Bezerker',
    trait: 'blue-collar',
    expansion: true,
    expected: 16,
    published: 15,
    spd: 1,
    def: '2d6',
    fp: '2d8',
    prw: '2d8',
    will: '2d8',
    ranged: ['energy-pistol'],
    close: ['melee-weapon'],
    equip: ['grenade'],
  }),
  // Xenos Bugs (Mutants)
  E({
    name: 'Big Bug',
    trait: 'mutants',
    expansion: true,
    expected: 24,
    leader: true,
    spd: 2,
    def: '2d8',
    fp: '2d8',
    prw: '2d8',
    will: '2d10',
    ranged: ['shotgun'],
    close: ['horrible-claws-teeth'],
    equip: ['heavy-armor'],
    powers: ['prescience', 'mind-control'],
  }),
  E({
    name: 'Flying Bug',
    trait: 'mutants',
    expansion: true,
    expected: 18,
    spd: 3,
    def: '2d8',
    fp: '2d8',
    prw: '2d8',
    will: '2d6',
    ranged: ['shotgun'],
    close: ['claws-teeth'],
    equip: ['jump-pack'],
  }),
  E({
    name: 'Grunt Bug',
    trait: 'mutants',
    expansion: true,
    expected: 13,
    spd: 2,
    def: '2d8',
    fp: '2d8',
    prw: '2d6',
    will: '2d6',
    ranged: ['shotgun'],
    close: ['claws-teeth'],
  }),
  E({
    name: 'Little Bugs',
    trait: 'mutants',
    expansion: true,
    expected: 8,
    published: 10,
    spd: 1,
    def: '2d6',
    fp: 'none',
    prw: '2d6',
    will: '2d6',
    close: ['horrible-claws-teeth'],
  }),
  // Neon City: Purifying Flame (Fanatics), Tech Bros (Cyborgs), Miners Guild (Blue Collar)
  E({
    name: 'Deacon Inferno',
    trait: 'fanatics',
    expansion: true,
    expected: 23,
    leader: true,
    spd: 2,
    def: '2d6',
    fp: '2d10',
    prw: '2d8',
    will: '2d10',
    ranged: ['flamer'],
    close: ['melee-weapon'],
    equip: ['grenade', 'grenade'],
    powers: ['fear'],
  }),
  E({
    name: 'Acolyte',
    trait: 'fanatics',
    expansion: true,
    expected: 12,
    spd: 2,
    def: '2d6',
    fp: '2d8',
    prw: '2d6',
    will: '2d6',
    ranged: ['heavy-pistol'],
    close: ['melee-weapon'],
    equip: ['grenade'],
  }),
  E({
    name: 'Tech Daddy',
    trait: 'cyborgs',
    expansion: true,
    expected: 21,
    published: 23,
    leader: true,
    spd: 2,
    def: '2d8',
    fp: '2d10',
    prw: '2d6',
    will: '2d6',
    ranged: ['sniper-rifle'],
    equip: ['stealth-suit', 'targeting-reticule', 'comms-unit'],
    powers: ['prescience'],
  }),
  E({
    name: 'Tech Bro',
    trait: 'cyborgs',
    expansion: true,
    expected: 14,
    spd: 2,
    def: '2d6',
    fp: '2d8',
    prw: '2d6',
    will: '2d6',
    ranged: ['energy-rifle'],
    equip: ['targeting-reticule', 'stealth-suit'],
  }),
  E({
    name: 'Foreman',
    trait: 'blue-collar',
    expansion: true,
    expected: 19,
    leader: true,
    spd: 2,
    def: '2d6',
    fp: '2d10',
    prw: '2d6',
    will: '2d8',
    ranged: ['autocannon'],
    close: ['melee-weapon'],
    equip: ['heavy-armor', 'targeting-reticule'],
  }),
  E({
    name: 'Crew',
    trait: 'blue-collar',
    expansion: true,
    expected: 12,
    spd: 2,
    def: '2d6',
    fp: '2d8',
    prw: '2d8',
    will: '2d6',
    ranged: ['auto-pistol'],
    close: ['melee-weapon'],
  }),
];

describe('example warbands from the PDFs', () => {
  for (const ex of examples) {
    it(`${ex.name} costs ${ex.expected}${ex.published ? ` (PDF prints ${ex.published})` : ''}`, () => {
      const model: ModelSpec = {
        ...newModel(ex.leader),
        name: ex.name,
        speed: ex.spd,
        defense: ex.def as ModelSpec['defense'],
        firepower: ex.fp as ModelSpec['firepower'],
        prowess: ex.prw as ModelSpec['prowess'],
        willpower: ex.will as ModelSpec['willpower'],
        rangedWeapons: ex.ranged ?? [],
        closeWeapons: ex.close ?? ['unarmed'],
        equipment: ex.equip ?? [],
        powers: ex.powers ?? [],
      };
      const ctx: Context = { expansion: !!ex.expansion, warbandTrait: ex.trait };
      expect(modelCost(model, ctx).total).toBe(ex.expected);
    });
  }
});
